#pragma once
//
// Created by Admin on 2022/10/25.
//

#ifndef GGXX_CLIENTINSTANCE_H
#define GGXX_CLIENTINSTANCE_H

#include "Global.h"
#include "GuiData.h"
#include "Actor.h"
#include "Player.h"
#include "Level.h"
#include "LocalPlayer.h"
#include "LocalPlayer.h"

class ClientInstance {
public:
    virtual __int64 destructorClientInstance();
    virtual __int64 onInitMinecraftGame();
    virtual __int64 onDestroyMinecraftGame();
    virtual __int64 init(__int64*, __int64&, __int64&, __int64&, __int64&, int);
    virtual __int64 initSceneFactory(__int64*);
    virtual __int64 initGraphics();
    virtual __int64 stop();
    virtual __int64 teardown();
    virtual __int64 preShutDown();
    virtual __int64 requestLeaveGame(bool, bool);
    virtual __int64 stopPlayScreen();
    virtual bool isLeaveGameDone() const;
    virtual void setupPlayScreenForLeaveGame();
    virtual __int64 resetPrimaryClient();
    virtual __int64 resetGameSession();
    virtual __int64 tick();
    virtual __int64 frameUpdate(__int64&);
    virtual __int64 update(bool);
    virtual __int64 endFrame();
    virtual __int64 startSubClientLateJoin(bool);
    virtual void setupClientGame(__int64&&, bool);
    virtual __int64 sub_1400C5D00() const;
    virtual LocalPlayer* getLocalPlayer();
    virtual LocalPlayer* getLocalPlayer() const;
    virtual __int64 getCameraEntity() const;
    virtual void setCameraEntity(Actor*);
    virtual __int64 getCameraTargetEntity() const;
    virtual void setCameraTargetEntity(Actor*);
    virtual bool isLeavingGame() const;
    virtual bool isDestroyingGame() const;
    virtual __int64 sub_1400C98E0() const;
    virtual __int64 useLowFrequencyUIRender() const;
    virtual bool isSplitScreenActive() const;
    virtual bool isVRClient() const;
    virtual bool isARClient() const;
    virtual bool isARVRClient() const;
    virtual bool isHoloviewerMode() const;
    virtual bool isHoloscreenMode() const;
    virtual bool isLivingroomMode() const;
    virtual bool isExitingLevel() const;
    virtual bool isNotVLRMode() const;
    virtual bool isHoloRealityMode() const;
    virtual bool isRealityFullVRMode() const;
    virtual bool isInBedScreen() const;
    virtual bool isKeyboardEnabled() const;
    virtual bool isVRTransitioning() const;
    virtual bool hasCommands() const;
    virtual bool isScriptingEnabled() const;
    virtual __int64 getHoloviewerScale() const;
    virtual __int64 getSplitScreenCount() const;
    virtual bool isStereoRendering() const;
    virtual bool isPlatformNX() const;
    virtual bool isLocalSplitscreenWith(__int64 const&) const;
    virtual bool isValidCrossPlatformSkin() const;
    virtual __int64 sub_1400C9B70();
    virtual __int64 getSplitScreenInfo() const;
    virtual __int64 getCurrentMaxGUIScaleIndex() const;
    virtual __int64 getRealityModeFrameFactor() const;
    virtual void setRealityModeFrameFactor(float const&);
    virtual __int64 getRealityModeToggleTriggered() const;
    virtual void setRealityModeToggleTriggered(bool);
    virtual bool sub_1400C9C50();
    virtual void setOpenControllerDisconnectScreen(bool);
    virtual __int64 getClientPlayMode() const;
    virtual void setClientPlayMode(__int64 const&);
    virtual __int64 getLivingRoomForCredits() const;
    virtual void setLivingRoomForCredits(bool);
    virtual __int64 getCreditsCallback();
    virtual void setCreditsCallback(__int64);
    virtual void setupTransitionForCredits(__int64);
    virtual __int64 refreshScreenSizeData();
    virtual __int64 onScreenSizeChanged(int, int, float);
    virtual __int64 onGuiScaleOffsetChanged();
    virtual __int64 onSafeZoneChanged();
    virtual __int64 quit(std::string const&, std::string const&);
    virtual __int64 getMinecraftGame() const;
    virtual __int64 getAutomationClient() const;
    virtual __int64 getScreenshotStreamer() const;
    virtual __int64 getEventing() const;
    virtual __int64 sub_1400CA2E0(__int64 a1);
    virtual __int64 sub_1400CA2E8(__int64 a1);
    virtual __int64 sub_1400CA2F0(__int64 a1);
    virtual void* getFont() const;
    virtual void* getRuneFont() const;
    virtual void* getUnicodeFont() const;
    virtual __int64 getGeometryGroup() const;
    virtual __int64 getMultiplayerServiceManager() const;
    virtual __int64 getLocalServerLevel();
    virtual __int64 getResourcePackRepository() const;
    virtual __int64 getResourcePackManager() const;
    virtual __int64 getSkinRepository() const;
    virtual __int64 getSkinRepositoryClientInterface() const;
    virtual __int64 sub_140630650() const;
    virtual void test0();
    virtual void test1();
    virtual __int64 sub_1400CA400() const;
    virtual __int64 getTextures() const;
    virtual __int64 getStoreCacheTextures() const;
    virtual __int64 getMinecraftGraphics() const;
    virtual __int64 getUIRepository() const;
    virtual __int64 getUserManager() const;
    virtual __int64 wantToQuit() const;
    virtual bool isPrimaryLevelCrossPlatformMultiplayer() const;
    virtual bool isPrimaryLevelMultiplayer() const;
    virtual bool isAdhocEnabled() const;
    virtual char sub_1406A1620() const;
    virtual __int64 linkToOffer(std::string const&, bool, std::string const&, __int64);
    virtual __int64 linkToAllOffers(std::string const&, std::string const&, bool, std::string const&, bool);
    virtual __int64 navigateToBrazeScreen(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::string const&);
    virtual __int64 navigateToStoreHomeScreen();
    virtual __int64 navigateToCoinPurchaseScreen(int, __int64);
    virtual __int64 navigateToPurchaseOfferScreen(__int64, bool);
    virtual __int64 navigateToOfferCollectionScreen(__int64&);
    virtual __int64 navigateToStoreSeeAllByCreatorScreen(std::string const&, bool);
    virtual __int64 navigateToServersScreen(bool);
    virtual __int64 navigateToHowToPlayScreen(std::string const&);
    virtual __int64 tryPushLeaveGameScreen();
    virtual char sub_1400D16A0() const;
    virtual bool isReadyToRender() const;
    virtual __int64 onDimensionChanged();
    virtual __int64 onGameEventNotification(__int64);
    virtual std::string getTopScreenName() const;
    virtual void setLeaveGameInProgressAsReadyToContinue();
    virtual __int64 stopDestroying();
    virtual __int64 onClientCreatedLevel(__int64);
    virtual __int64 getClientRandomId() const;
    virtual __int64 getUserAuthentication();
    virtual __int64 sub_1400CAC50(__int64* a2);
    virtual __int64 registerToUserManager(__int64&, int);
    virtual __int64 resumeWithUserManager(__int64&, int);
    virtual __int64 createUserAuthentication(std::string);
    virtual __int64 createUserAuthentication(unsigned long long, std::string const&);
    virtual __int64 getPlatformId() const;
    virtual __int64 getPlatformOnlineId() const;
    virtual bool isHoloCursorNeeded() const;
    virtual __int64 useController() const;
    virtual __int64 useTouchscreen() const;
    virtual void subFunction1() const;
    virtual void subFunction2() const;
    virtual void subFunction3() const;
    virtual void subFunction4() const;
    virtual void subFunction5() const;
    virtual void subFunction6() const;
    virtual void subFunction7() const;
    virtual bool getMouseGrabbed() const;
    virtual __int64 currentInputModeIsGamePadOrMotionController() const;
    virtual __int64 currentInputModeIsMouseAndKeyboard() const;
    virtual __int64 getForceMonoscopic() const;
    virtual __int64 allowPicking() const;
    virtual bool isShowingMenu() const;
    virtual bool isShowingProgressScreen() const;
    virtual bool isShowingWorldProgressScreen() const;
    virtual bool isShowingDeathScreen() const;
    virtual bool isScreenReplaceable() const;
    virtual bool isInGame() const;
    virtual bool sub_14070D6F0() const;
    virtual bool isInRealm();
    virtual __int64 readyForShutdown() const;
    virtual bool isPrimaryClient() const;
    virtual bool isEduMode() const;
    virtual bool isGamepadCursorEnabled() const;
    virtual void* getServerData();
    virtual void* getServerData() const;
    virtual Level* getLevel();
    virtual Level* getLevel() const;
    virtual bool isPreGame() const;
    virtual bool isInMultiplayerGame() const;
    virtual bool isMultiC_PlayerClient() const;
    virtual __int64 sub_14012F590() const;
    virtual __int64 sub_14012F4D0() const;
    virtual __int64 getOptions();
    virtual __int64 getOptions() const;
    //virtual __int64 getOptionsPtr();
    virtual __int64 getUser();
    virtual __int64 getUser() const;
    virtual __int64 getGameRenderer() const;
    virtual __int64 getHolosceneRenderer() const;
    virtual __int64 getLevelRenderer() const;
    virtual __int64 getLevelRendererCameraProxy() const;
    virtual void* getCameraManager() const;
    virtual __int64 sub_1400CCC08() const;
    virtual __int64 getLightTexture();
    virtual void setupLevelRendering(__int64&, Actor&);
    virtual __int64 getViewportInfo() const;
    virtual void setViewportInfo(__int64 const&);
    virtual __int64 getNormalizedViewportSize() const;
    virtual __int64 updateChunkRadius();
    virtual void setUITexture(__int64*);
    virtual __int64 getUITexture();
    virtual void setLevelTexture(__int64*);
    virtual __int64 getLevelTexture();
    virtual void setUICursorTexture(__int64);
    virtual __int64 getUICursorTexture() const;
    virtual __int64 getCamera();
    virtual __int64 getShaderColor();
    virtual __int64 getDarkShaderColor();
    virtual __int64 clearGraphicsCache();
    virtual __int64 getNormalizedUICursorTransform(__int64&, float);
    virtual __int64 shouldRenderUICursor() const;
    virtual bool sub_1400CD3B0();
    virtual bool sub_1400CD3B1();
    virtual __int64 getGuiScale() const;
    virtual __int64 getGuiScaleOption() const;
    virtual __int64 getGuiScaleOffset() const;
    virtual void setGuiScaleOffset(int);
    virtual __int64 renderEditorGui(__int64&, bool);
    virtual GuiData* getGuiDataDOESNTWORK();
    virtual GuiData* getGuiDataDOESNTWORK() const;
    virtual __int64 getGuidedFlowManager();
    virtual __int64 getDpadScale() const;
    virtual __int64 getDateManager() const;
    virtual __int64 addOverrideHoursToDateTime(unsigned int);
    virtual __int64 getToastManager();
    virtual __int64 getTopScene();
    virtual __int64 getTopScene() const;
    virtual __int64 getActiveScene();
    virtual __int64 getActiveScene() const;
    virtual __int64 getSceneFactory() const;
    virtual __int64 getClientSceneStack() const;
    virtual __int64 getClientSceneStack();
    virtual __int64 sub_140634B30() const;
    virtual __int64 getMainSceneStack();
    virtual __int64 getMainSceneStack() const;
    virtual __int64 getCurrentSceneStack() const;
    virtual __int64 getCurrentSceneStack();
    virtual __int64 getCurrentUIRouter();
    virtual __int64 getCurrentUIRouter() const;
    virtual __int64 sub_14012BAB0() const;
    virtual __int64 prepareSceneFor(__int64);
    virtual __int64 getCachedScenes();
    virtual std::string getScreenName() const;
    virtual __int64 getScreenTelemetry() const;
    virtual __int64 getTopSceneType() const;
    virtual __int64 getMobEffectsLayout();
    virtual __int64 newFunc2(__int64 a2, __int64 a3, char a4);
    virtual __int64 newFunc3(__int64 a2, __int64 a3);
    virtual __int64 onMobEffectsChange();
    virtual void setUISizeAndScale(int, int, float);
    virtual __int64 forEachVisibleScreen(__int64, bool);
    virtual __int64 forEachScreen(__int64, bool);
    virtual __int64 forEachScreenConst(__int64, bool) const;
    virtual __int64 updateSceneStack();
    virtual __int64 forEachAlwaysAcceptInputScreen(__int64);
    virtual __int64 forEachAlwaysAcceptInputScreenWithTop(__int64);
    virtual __int64 showC_PlayerProfile(std::string const&, __int64);
    virtual __int64 getCurrentInputMode() const;
    virtual bool isTouchGameplayAllowed() const;
    virtual __int64 getMinecraftInput() const;
    virtual void setHoloInput(__int64);
    virtual __int64 getHoloInput() const;
    virtual __int64 getVoiceSystem() const;
    virtual __int64 getKeyboardManager();
    virtual void setVoiceSystem(__int64);
    virtual void setLastPointerLocation(float, float, float);
    virtual __int64 getLastPointerLocation();
    virtual __int64 shouldUseLastPointerLocationOnFocusChange();
    virtual __int64 adjustGazeCursorByMouse(float, float);
    virtual __int64 currentScreenShouldStealMouse();
    virtual __int64 getInProgressBAI() const;
    virtual __int64 newDictationDataAvailable() const;
    virtual __int64 clearDictationDataAvailable();
    virtual __int64 getDictationText() const;
    virtual __int64 getPacketSender();
    virtual __int64 getClientNetworkSystem();
    virtual __int64 getClientNetworkSystem() const;
    virtual void fake_function_to_make_grabmouse_work() const;
    virtual void setMoveTurnInput(__int64);
    virtual void* getMoveTurnInput();
    virtual void setupPersistentControls(__int64);
    virtual __int64 resetC_PlayerMovement();
    virtual __int64 onClientInputInitComplete();
    virtual void setClientInputHandler(__int64);
    virtual __int64 getInput() const;
    virtual __int64 getControllerId() const;
    virtual bool hasConnectedController() const;
    virtual __int64 getClientSubId() const;
    virtual void setSuspendInput(bool);
    virtual void setDisableInput(bool);
    virtual void subFunction() const;
    virtual void grabMouse();
    virtual void releaseMouse();
    virtual void refocusMouse();
    virtual __int64 resetBai(int);
    virtual __int64 clearInProgressBAI();
    virtual __int64 tickBuildAction();
    virtual __int64 getSoundEngine() const;
    virtual __int64 play(std::string const&, Vec3 const&, float, float);
    virtual __int64 playUI(std::string const&, float, float);
    virtual __int64 muteAudio();
    virtual __int64 unMuteAudio();
    virtual __int64 fadeOutMusic() const;
    virtual __int64 getTaskGroup();
    virtual __int64 onFullVanillaPackOnStack();
    virtual bool isFullVanillaPackOnStack() const;
    virtual __int64 onPlayerLoaded(Player&);
    virtual void setClientGameMode(__int64);
    virtual __int64 resetToDefaultGameMode();
    virtual __int64 connectToThirdParyServer(std::string const&, std::string const&, int);
    virtual __int64 startExternalNetworkWorld(__int64, std::string const&, bool);
    virtual __int64 checkForPiracy();
    virtual __int64 updateChatFilterStatus();
    virtual void sub_1400D2A20();
    virtual void setBehaviorCommandCallback(__int64);
    virtual void setBehaviorCommandStatus(std::string, __int64);
    virtual __int64 requestScreenshot(__int64&);
    virtual void sub_1400BE0A0(char a2);
    virtual __int64 getDevConsoleLogger() const;
    virtual __int64 requestImageFromUrl(std::string const&, __int64);
    virtual __int64 initializeRenderResources();
    virtual __int64 postInitRenderResources();
    virtual __int64 onAppSuspended();
    virtual __int64 onActiveResourcePacksChanged(__int64 const&);
    virtual __int64 reloadEntityRenderers(__int64 const&);
    virtual __int64 getBlockTessellator();
    virtual __int64 getBlockEntityRenderDispatcher();
    virtual __int64 getEntityRenderDispatcher();
    virtual __int64 getEntityBlockRenderer();
    virtual __int64 getItemInHandRenderer();
    virtual __int64 getItemRenderer();
    virtual __int64 getSentMessageHistory();
    virtual __int64 getUIProfanityContext() const;
    virtual __int64 initTTSClient(__int64&);
    virtual __int64 getTTSClient();
    virtual __int64 getTTSClient() const;
    virtual __int64 getTTSEventManager();
    virtual __int64 addTTSMessage(std::string const&, __int64, bool, bool, bool);
    virtual __int64 initCommands();
    virtual __int64 getUserId() const;
    virtual __int64 getServerConnectionTime() const;
    virtual __int64 getHMDState();
    virtual __int64 getHMDState() const;
    virtual void setServerPingTime(unsigned int);
    virtual __int64 getServerPingTime() const;
    virtual void setDefaultPlayscreenTab(__int64);
    virtual void setClientInstanceState(__int64 const&);
    virtual void setUIEventCoordinator(__int64&&);
    virtual __int64 getUIEventCoordinator();
    virtual __int64 getEventCoordinator();
    virtual __int64 computeScreenCoordsFromScreenNormCoords(float, float, short&, short&);
    virtual __int64 getNoBlockBreakUntil();
    virtual void setNoBlockBreakUntil(__int64);
    virtual void setDictation(std::string const&);
    virtual void setNewDictationString(bool);
    virtual void setGameModule(__int64);
    virtual __int64 getGameModule();
    virtual __int64 getGameCallbacks();
    virtual __int64 getStorageAreaStateListener();
    virtual __int64 getScriptEngine();
    virtual __int64 sendClientEnteredLevel();
    virtual __int64 getHitDetectSystem();
    virtual bool isPlaying() const;
    virtual __int64 getLatencyGraphDisplay() const;
    virtual __int64 createSkin();
    virtual __int64 onExtendDiskSpace(bool, __int64&, unsigned long long const&, __int64);
    virtual __int64 onLowDiskSpace(bool);
    virtual __int64 onOutOfDiskSpace(bool);
    virtual __int64 onCriticalDiskError(bool, __int64 const&);
    virtual __int64 onLevelCorrupt();
    virtual __int64 onGameModeChanged();
    virtual __int64 onTick(int, int);
    virtual __int64 onInternetUpdate();
    virtual __int64 onGameSessionReset();
    virtual __int64 onLevelExit();
    virtual __int64 updateScreens();


};


#endif //GGXX_CLIENTINSTANCE_H
